import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import commerceService from '../services/commerceService'
import '../styles/portal.css'

const steps = ['Address', 'Delivery', 'Payment', 'Confirmation']
export function CheckoutPage() {
  const [step, setStep] = useState(0); const [addresses, setAddresses] = useState([]); const [addressId, setAddressId] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { commerceService.getAddresses().then((items) => { const available = items || []; setAddresses(available); setAddressId(available.find((item) => item.isDefault)?.id || available[0]?.id || '') }).catch((error) => setMessage(error.message)) }, [])
  const next = async () => { if (step === 0 && !addressId) return setMessage('Please select a saved delivery address.') ; if (step === 2) { try { await commerceService.createOrder(Number(addressId)); setStep(3) } catch (error) { setMessage(error.message) } } else setStep(Math.min(3, step + 1)) }
  return <div className="checkout-page"><div className="page-heading"><span className="eyebrow">SECURE CHECKOUT</span><h1>Complete your order</h1></div><div className="checkout-steps">{steps.map((label, index) => <div className={index <= step ? 'active' : ''} key={label}><span>{index + 1}</span>{label}</div>)}</div>{message && <div className="shop-notice">{message}</div>}<div className="checkout-card">{step === 0 && <div><h2>Where should we deliver?</h2><p className="muted">Select one of your saved addresses. Add addresses from your account profile.</p>{addresses.length ? <div className="address-options">{addresses.map((address) => <label className="choice-card" key={address.id}><input type="radio" name="address" checked={String(addressId) === String(address.id)} onChange={() => setAddressId(address.id)} />{address.addressLine}<span>{address.city}, {address.state} {address.postalCode}, {address.country}</span></label>)}</div> : <div className="empty-state">No saved addresses are available yet. Add one in your profile before checkout.</div>}</div>}{step === 1 && <div><h2>Delivery method</h2><label className="choice-card"><input type="radio" defaultChecked name="delivery" /> Standard delivery <span>Delivery details supplied by the order service</span></label></div>}{step === 2 && <div><h2>Payment</h2><label className="choice-card"><input type="radio" defaultChecked name="payment" /> Pay on the available checkout method <span>Payment provider integration is not exposed by the current backend.</span></label></div>}{step === 3 && <div className="confirmation"><span>✓</span><h2>Order request received</h2><p>Your order has been created. You can follow its status from your orders page.</p><Link to="/orders" className="hero-button">View my orders</Link></div>}<div className="checkout-actions">{step > 0 && step < 3 && <button className="outline-button" onClick={() => setStep(step - 1)}>Back</button>}{step < 3 && <button className="hero-button" onClick={next}>{step === 2 ? 'Place order' : 'Continue'}</button>}{step === 0 && <Link to="/cart" className="text-link">Return to cart</Link>}</div></div></div>
}
